# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e29dfee095e3ebbf2047dfcb855276a402ee274d862cf3117e8a2caff5c50f0fc648d87f6977dc296ef318f64b338e29221d8f64a9d69543da21d540838f960

test:
  secret_key_base: 65782d94fb20494a28ccc72deffcae5919eb2ec7c77805895045b94bc2706eb97a539c12ac2f6f05f1ccf485a1b26b7d5574c3ece4c0da21732189c9cab6678d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
